import {
	ImgHero,
	ImgHeroDefault,
	ImgAboutMe,
	ImgAboutMeDefault,
	ImgEkNepalLogo,
	ImgEkNepalLogoDefault,
	ImgTimeeroLogo,
	ImgTimeeroLogoDefault,
	ImgVersuredLogo,
	ImgVersuredLogoDefault,
} from 'assets/images';
import {
	IconLink,
	IconLinkDefault,
	IconFacebookDefault,
	IconFacebook,
	IconGithubDefault,
	IconGithub,
	IconInstagramDefault,
	IconInstagram,
	IconLinkedInDefault,
	IconLinkedIn,
} from './icons';

export {
	ImgHero,
	ImgHeroDefault,
	ImgAboutMe,
	ImgAboutMeDefault,
	ImgEkNepalLogo,
	ImgEkNepalLogoDefault,
	ImgTimeeroLogo,
	ImgTimeeroLogoDefault,
	ImgVersuredLogo,
	ImgVersuredLogoDefault,
	IconLink,
	IconLinkDefault,
	IconFacebookDefault,
	IconFacebook,
	IconGithubDefault,
	IconGithub,
	IconInstagramDefault,
	IconInstagram,
	IconLinkedInDefault,
	IconLinkedIn,
};
